version:  '3.3'

services:

  nginx:
    image: nginx:1.22-alpine
    restart: on-failure
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "443:443"
      - "80:80"

  php:
    build:
      context: docker/php
    volumes:
      - '.:/app'
    restart: on-failure
#    environment:
#      - 'XDEBUG_MODE=develop,debug'
    depends_on:
      - database

  database:
    image: mariadb:10.10
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: things

  cron:
    image: alpine:latest
    command: "crond -f -l 0 -L /dev/stdout"
    volumes:
      - './docker/crontab/crontab:/var/spool/cron/crontabs/root:rwx'

volumes:
  db-data:

